name: Docker Image build 
on: 
  push: 
    branches:
      - main 
  pull_request:
    branches:
      - main 
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code 
        uses: actions/checkout@v4 
      - name: build api image
        run: docker build -f apps/api-python/Dockerfile -t cvht-api:${{ github.sha }} . 
      - name: build worker image
        run: docker build -f apps/worker/Dockerfile -t cvht-worker:${{ github.sha }} . 
      - name: build web image
        run: docker build -f apps/web/Dockerfile -t cvht-web${{ github.sha }} .
      
